# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'Gemfile', 'Gemfile.lock', 'Procfile', 'vendor', 'gems']
markdown: rdiscount
domain: www.example.com
title: Jekyll Less Heroku
author: Your Name
email: you@example.com